apiVersion: v1
kind: Service
metadata:
  name: besu-bootnode
spec:
  selector:
    app: bootnode
  ports:
    - port: 30303
      targetPort: 30303
      protocol: UDP
      name: discovery
    - port: 30303
      targetPort: 30303
      protocol: TCP
      name: rlpx
    - port: 8545
      targetPort: 8545
      protocol: TCP
      name: json-rpc
