apiVersion: v1
kind: Service
metadata:
  name: besu-node
  labels:
    app: node
spec:
  type: ClusterIP
  selector:
    app: node
  ports:
    - port: 30303
      targetPort: 30303
      protocol: UDP
      name: discovery
    - port: 30303
      targetPort: 30303
      protocol: TCP
      name: rlpx
    - port: 8545
      targetPort: 8545
      protocol: TCP
      name: json-rpc
