apiVersion: v1
kind: ConfigMap
metadata:
  name: besu-config-toml-configmap
  labels:
    app: besu-config-toml-configmap
data:
  config.toml: |-
    # Node Information
    data-path="/data"
    genesis-file="/etc/genesis/genesis.json"
    network-id = "1000001"
    
    # P2P network
    p2p-host="0.0.0.0"
    p2p-port=30303

    host-allowlist=["*"]

    # JSON-RPC
    rpc-http-enabled=true
    rpc-http-host="0.0.0.0"
    rpc-http-port=8545
    rpc-http-api=["DEBUG","ETH", "ADMIN", "WEB3", "IBFT", "NET", "TXPOOL", "DEBUG", "TRACE", "PLUGINS"]
    rpc-http-cors-origins=["*"]


    # ethstats="${POD_NAME}:itskba@${BESU-DASHBOARD_SERVICE_HOST}:3000"
